// Code generated by go test -run GoldenInside -update; DO NOT EDIT.

package main

var goldenInsideWant = map[string]string{
	"api-keys-create-network": `== stdout
{}
== stderr
== writes
POST /v1/keys {"name":"ci","permissions":["network"]}
`,
	"api-keys-set-legacy-names": `== stdout
{}
== stderr
proxies, profiles: no longer a permission; changing a browser's proxies or moving its profile needs none (ask the user first)
== writes
PATCH /v1/keys/k1 {"permissions":["network","proxies","profiles"]}
`,
	"api-keys-set-network": `== stdout
{}
== stderr
== writes
PATCH /v1/keys/k1 {"permissions":["billing","network"]}
`,
	"browser-api-create-reachable-from": `== stdout
{
  "created": "pool2",
  "next": "livellm connect pool2 gives its address and a key or token",
  "type": "controller"
}
== stderr
== writes
POST /v1/workloads/controller {"autodiscover":false,"browsers":["b1"],"id":"pool2","reachableFrom":["edge","box"]}
`,
	"connect-inside": `== stdout
{
  "engine": "postgres",
  "inside": {
    "addresses": [
      {
        "host": "ws-db-rw",
        "port": 5432
      }
    ],
    "alsoFrom": [
      {
        "id": "web",
        "why": "links it"
      },
      {
        "id": "desk",
        "why": "links it"
      }
    ]
  },
  "private": {
    "host": "ws-db-rw",
    "port": 5432
  },
  "tool": "api",
  "type": "storage"
}
== stderr
inside the workspace: reached only by what links it: web (links it), desk (links it)
== writes
POST /v1/workloads/db/connect {}
`,
	"connect-object-storage": `== stdout
{
  "accessKey": "filesapp",
  "bucket": "app",
  "console": "https://files-admin-ws.apps.example/rustfs/console/",
  "engine": "s3",
  "inside": {
    "addresses": [
      {
        "host": "ws-files",
        "port": 9000
      }
    ],
    "alsoFrom": [
      {
        "id": "uploader",
        "why": "links it"
      }
    ]
  },
  "private": {
    "endpoint": "http://ws-files:9000",
    "host": "ws-files",
    "port": 9000
  },
  "public": {
    "endpoint": "https://files-ws.apps.example",
    "host": "files-ws.apps.example",
    "pathStyle": true,
    "port": 443
  },
  "region": "us-east-1",
  "secretKey": "set when the object storage was made; it can't be read back",
  "tool": "api",
  "type": "storage"
}
== stderr
inside the workspace: reached only by what links it: uploader (links it)
== writes
POST /v1/workloads/files/connect {}
`,
	"create-apps-join-no-reachable-from": `== stdout
{
  "created": null
}
== stderr
== writes
POST /v1/workloads {"apps":[{"id":"cron","image":"busybox"}],"join":"web"}
`,
	"create-apps-join-same-reachable-from": `== stdout
{
  "created": null
}
== stderr
== writes
POST /v1/workloads {"apps":[{"id":"cron","image":"busybox","reachableFrom":["edge"]}],"join":"shop"}
`,
	"create-apps-no-reachable-from": `== stdout
{
  "created": null
}
== stderr
== writes
POST /v1/workloads {"apps":[{"id":"front","image":"nginx"}]}
`,
	"create-apps-reachable-from": `== stdout
{
  "created": null
}
== stderr
== writes
POST /v1/workloads {"apps":[{"databases":[{"id":"pg"}],"id":"front","image":"nginx","reachableFrom":["edge"]},{"id":"back","image":"busybox","reachableFrom":["edge"]}],"databases":[{"engine":"postgres","id":"pg"}]}
`,
	"create-browser-reachable-from": `== stdout
{
  "created": "shop",
  "type": "browser"
}
== stderr
== writes
POST /v1/workloads/browser {"id":"shop","reachableFrom":["pool"]}
`,
	"create-database-reachable-from-none": `== stdout
{
  "created": "db2",
  "type": "storage"
}
== stderr
a database has no --reachable-from: only what links it reaches it (left out)
== writes
POST /v1/workloads/storage {"engine":"redis","id":"db2"}
`,
	"create-desktop-database": `== stdout
{
  "created": "d2",
  "type": "desktop"
}
== stderr
== writes
POST /v1/workloads/desktop {"databases":[{"id":"db"}],"id":"d2"}
`,
	"create-file-reachable-from": `== stdout
{
  "created": "api",
  "type": "pod"
}
== stderr
== writes
POST /v1/workloads/pod {"id":"api","image":"nginx","reachableFrom":["*"]}
`,
	"create-file-reachable-from-none": `== stdout
{
  "created": "api2",
  "type": "pod"
}
== stderr
== writes
POST /v1/workloads/pod {"id":"api2","image":"nginx","reachableFrom":[]}
`,
	"create-vm-database": `== stdout
{
  "created": "m2",
  "type": "vm-ubuntu"
}
== stderr
== writes
POST /v1/workloads/vm-ubuntu {"databases":[{"id":"lone"},{"id":"cache"},{"id":"db"}],"id":"m2"}
`,
	"link-already": `== stdout
{
  "databases": [
    "cache"
  ],
  "id": "box",
  "note": "nothing to add: already linked"
}
== stderr
== writes

`,
	"link-app": `== stdout
{
  "databases": [
    "cache",
    "db"
  ],
  "id": "edge",
  "linked": [
    "db"
  ],
  "note": "reach only: no variables, the app doesn't restart"
}
== stderr
== writes
PATCH /v1/workloads/edge {"pod":{"databases":[{"id":"cache"},{"id":"db"}]}}
`,
	"link-app-stack": `== stdout
{
  "app": "shop",
  "databases": [
    "cache",
    "lone"
  ],
  "id": "worker",
  "linked": [
    "cache",
    "lone"
  ],
  "note": "reach only: no variables, the app doesn't restart; the whole Composable App shop reaches cache, lone"
}
== stderr
== writes
PATCH /v1/workloads/worker {"pod":{"databases":[{"id":"cache"},{"id":"lone"}]}}
`,
	"link-by-app-name": `== stdout
{
  "app": "shop",
  "databases": [
    "db",
    "lone"
  ],
  "id": "web",
  "linked": [
    "lone"
  ],
  "note": "reach only: no variables, the app doesn't restart; linked from web, the first service of shop; the whole Composable App shop reaches lone"
}
== stderr
== writes
PATCH /v1/workloads/web {"pod":{"databases":[{"env":{"DATABASE_URL":"url"},"id":"db"},{"id":"lone"}]}}
`,
	"link-desktop": `== stdout
{
  "databases": [
    "db",
    "cache"
  ],
  "id": "desk",
  "linked": [
    "cache"
  ],
  "note": "reach only: nothing goes into the Desktop App"
}
== stderr
== writes
PATCH /v1/workloads/desk {"desktop":{"databases":[{"id":"db"},{"id":"cache"}]}}
`,
	"link-machine": `== stdout
{
  "databases": [
    "cache",
    "db"
  ],
  "id": "win",
  "linked": [
    "cache",
    "db"
  ],
  "note": "reach only: nothing goes into the machine"
}
== stderr
== writes
PATCH /v1/workloads/win {"vm":{"databases":[{"id":"cache"},{"id":"db"}]}}
`,
	"link-object-storage-already": `== stdout
{
  "databases": [
    "files"
  ],
  "id": "uploader",
  "note": "nothing to add: already linked"
}
== stderr
== writes

`,
	"link-object-storage-app": `== stdout
{
  "databases": [
    "cache",
    "files"
  ],
  "id": "edge",
  "linked": [
    "files"
  ],
  "note": "reach only: no variables, the app doesn't restart"
}
== stderr
== writes
PATCH /v1/workloads/edge {"pod":{"databases":[{"id":"cache"},{"id":"files"}]}}
`,
	"link-object-storage-machine": `== stdout
{
  "databases": [
    "files"
  ],
  "id": "win",
  "linked": [
    "files"
  ],
  "note": "reach only: nothing goes into the machine"
}
== stderr
== writes
PATCH /v1/workloads/win {"vm":{"databases":[{"id":"files"}]}}
`,
	"link-remove-machine": `== stdout
{
  "databases": [],
  "id": "box",
  "removed": [
    "cache"
  ]
}
== stderr
== writes
PATCH /v1/workloads/box {"vm":{"databases":[]}}
`,
	"link-remove-not-linked": `== stdout
{
  "databases": [
    "cache"
  ],
  "id": "edge",
  "note": "nothing to take out: not linked: db"
}
== stderr
== writes

`,
	"link-remove-with-variables": `== stdout
{
  "app": "shop",
  "databases": [],
  "id": "web",
  "note": "db's variables leave web: it restarts",
  "removed": [
    "db"
  ]
}
== stderr
== writes
PATCH /v1/workloads/web {"pod":{"databases":[]}}
`,
	"link-some-already": `== stdout
{
  "already": [
    "cache"
  ],
  "databases": [
    "cache",
    "lone"
  ],
  "id": "box",
  "linked": [
    "lone"
  ],
  "note": "reach only: nothing goes into the machine"
}
== stderr
== writes
PATCH /v1/workloads/box {"vm":{"databases":[{"id":"cache"},{"id":"lone"}]}}
`,
	"reach-set-from": `== stdout
{
  "id": "edge",
  "means": "only these",
  "reachableFrom": [
    "web",
    "box"
  ]
}
== stderr
== writes
PATCH /v1/workloads/edge {"reachableFrom":["web","box"]}
`,
	"reach-set-none": `== stdout
{
  "app": "shop",
  "id": "web",
  "means": "nothing else in the workspace",
  "note": "the whole Composable App shop takes it",
  "reachableFrom": []
}
== stderr
== writes
PATCH /v1/workloads/web {"reachableFrom":[]}
`,
	"reach-set-star": `== stdout
{
  "id": "edge",
  "means": "the whole workspace",
  "reachableFrom": [
    "*"
  ]
}
== stderr
== writes
PATCH /v1/workloads/edge {"reachableFrom":["*"]}
`,
	"reach-show-absent": `== stdout
{
  "addresses": [],
  "alsoFrom": [],
  "change": "livellm reach old --from a,b | --from \"*\" | --none",
  "id": "old",
  "means": "not set yet",
  "note": "until the platform closes this workspace, the whole workspace may still reach it; this is no setting that lets the whole workspace in (letting anything reach it still needs the user's agreement)",
  "reachableFrom": null
}
== stderr
== writes

`,
	"reach-show-app": `== stdout
{
  "addresses": [
    {
      "host": "ws-web",
      "inStack": "web:8080",
      "name": "http",
      "port": 8080
    },
    {
      "host": "ws-web-raw",
      "inStack": "web:7777",
      "name": "game",
      "port": 7777,
      "protocol": "udp"
    }
  ],
  "alsoFrom": [
    {
      "id": "worker",
      "why": "same app"
    }
  ],
  "app": "shop",
  "change": "livellm reach web --from a,b | --from \"*\" | --none",
  "id": "web",
  "joins": "a service added to shop reaches every service of it: adding one lets it in (ask the user first)",
  "means": "only these",
  "reachableFrom": [
    "edge"
  ]
}
== stderr
== writes

`,
	"reach-show-browser-api": `== stdout
{
  "addresses": [
    {
      "host": "ws-pool",
      "port": 8000
    }
  ],
  "alsoFrom": [],
  "change": "livellm reach pool --from a,b | --from \"*\" | --none",
  "id": "pool",
  "means": "only these",
  "reachableFrom": [
    "edge"
  ]
}
== stderr
== writes

`,
	"reach-show-browser-driven": `== stdout
{
  "addresses": [
    {
      "host": "ws-b1",
      "port": 9222
    },
    {
      "host": "ws-b1",
      "port": 9000
    }
  ],
  "alsoFrom": [
    {
      "id": "pool",
      "through": [
        "edge"
      ],
      "why": "drives it"
    },
    {
      "id": "every",
      "through": null,
      "why": "drives it"
    }
  ],
  "change": "livellm reach b1 --from a,b | --from \"*\" | --none",
  "id": "b1",
  "means": "nothing else in the workspace",
  "reachableFrom": []
}
== stderr
== writes

`,
	"reach-show-browser-driven-closed": `== stdout
{
  "addresses": [
    {
      "host": "ws-b1",
      "port": 9222
    },
    {
      "host": "ws-b1",
      "port": 9000
    }
  ],
  "alsoFrom": [
    {
      "id": "pool",
      "through": [
        "edge"
      ],
      "why": "drives it"
    },
    {
      "id": "every",
      "through": [
        "*"
      ],
      "why": "drives it"
    }
  ],
  "change": "livellm reach b1 --from a,b | --from \"*\" | --none",
  "id": "b1",
  "means": "nothing else in the workspace",
  "reachableFrom": []
}
== stderr
== writes

`,
	"reach-show-closed": `== stdout
{
  "alsoFrom": [],
  "change": "livellm reach edge --from a,b | --from \"*\" | --none",
  "id": "edge",
  "means": "nothing else in the workspace",
  "reachableFrom": []
}
== stderr
== writes

`,
	"reach-show-database-linked": `== stdout
{
  "addresses": [
    {
      "host": "ws-db-rw",
      "port": 5432
    }
  ],
  "alsoFrom": [
    {
      "app": "shop",
      "id": "web",
      "why": "links it"
    },
    {
      "app": "shop",
      "id": "worker",
      "via": "web",
      "why": "links it"
    },
    {
      "id": "desk",
      "why": "links it"
    }
  ],
  "change": "livellm link APP|MACHINE db (--remove takes a link out)",
  "id": "db",
  "means": "only what links it",
  "note": "the platform hasn't closed this workspace yet: until it does, the whole workspace may still reach it"
}
== stderr
== writes

`,
	"reach-show-database-linked-closed": `== stdout
{
  "addresses": [
    {
      "host": "ws-db-rw",
      "port": 5432
    }
  ],
  "alsoFrom": [
    {
      "app": "shop",
      "id": "web",
      "why": "links it"
    },
    {
      "app": "shop",
      "id": "worker",
      "via": "web",
      "why": "links it"
    },
    {
      "id": "desk",
      "why": "links it"
    }
  ],
  "change": "livellm link APP|MACHINE db (--remove takes a link out)",
  "id": "db",
  "means": "only what links it"
}
== stderr
== writes

`,
	"reach-show-database-redis": `== stdout
{
  "addresses": [
    {
      "host": "ws-cache",
      "port": 6379
    }
  ],
  "alsoFrom": [
    {
      "app": "shop",
      "id": "web",
      "via": "worker",
      "why": "waits for it"
    },
    {
      "app": "shop",
      "id": "worker",
      "why": "waits for it"
    },
    {
      "id": "edge",
      "why": "links it"
    },
    {
      "id": "box",
      "why": "links it"
    }
  ],
  "change": "livellm link APP|MACHINE cache (--remove takes a link out)",
  "id": "cache",
  "means": "only what links it",
  "note": "the platform hasn't closed this workspace yet: until it does, the whole workspace may still reach it"
}
== stderr
== writes

`,
	"reach-show-database-unlinked": `== stdout
{
  "alsoFrom": [],
  "change": "livellm link APP|MACHINE lone (--remove takes a link out)",
  "id": "lone",
  "means": "only what links it",
  "note": "nothing links it yet; the platform hasn't closed this workspace yet: until it does, the whole workspace may still reach it"
}
== stderr
== writes

`,
	"reach-show-database-unlinked-closed": `== stdout
{
  "alsoFrom": [],
  "change": "livellm link APP|MACHINE lone (--remove takes a link out)",
  "id": "lone",
  "means": "only what links it",
  "note": "nothing links it yet"
}
== stderr
== writes

`,
	"reach-show-desktop": `== stdout
{
  "alsoFrom": [],
  "change": "livellm reach desk --from a,b | --from \"*\" | --none",
  "id": "desk",
  "means": "nothing else in the workspace",
  "reachableFrom": []
}
== stderr
== writes

`,
	"reach-show-machine": `== stdout
{
  "addresses": [
    {
      "host": "ws-box",
      "name": "ssh",
      "port": 22
    },
    {
      "host": "ws-box-http",
      "name": "web",
      "port": 8080
    },
    {
      "host": "ws-box",
      "name": "pg",
      "port": 5432
    },
    {
      "host": "ws-box",
      "name": "dns",
      "port": 53,
      "protocol": "udp"
    },
    {
      "host": "ws-box-internal",
      "name": "etcd",
      "port": 2380
    }
  ],
  "alsoFrom": [],
  "change": "livellm reach box --from a,b | --from \"*\" | --none",
  "id": "box",
  "means": "the whole workspace",
  "reachableFrom": [
    "*"
  ]
}
== stderr
== writes

`,
	"reach-show-object-storage": `== stdout
{
  "addresses": [
    {
      "host": "ws-files",
      "port": 9000
    }
  ],
  "alsoFrom": [
    {
      "id": "uploader",
      "why": "links it"
    }
  ],
  "change": "livellm link APP|MACHINE files (--remove takes a link out)",
  "id": "files",
  "means": "only what links it",
  "note": "the platform hasn't closed this workspace yet: until it does, the whole workspace may still reach it"
}
== stderr
== writes

`,
	"reach-show-object-storage-closed": `== stdout
{
  "addresses": [
    {
      "host": "ws-files",
      "port": 9000
    }
  ],
  "alsoFrom": [
    {
      "id": "uploader",
      "why": "links it"
    }
  ],
  "change": "livellm link APP|MACHINE files (--remove takes a link out)",
  "id": "files",
  "means": "only what links it"
}
== stderr
== writes

`,
	"reach-show-windows": `== stdout
{
  "addresses": [
    {
      "host": "ws-win",
      "name": "ssh",
      "port": 22
    },
    {
      "host": "ws-win-rdp",
      "name": "rdp",
      "port": 3389
    }
  ],
  "alsoFrom": [],
  "change": "livellm reach win --from a,b | --from \"*\" | --none",
  "id": "win",
  "means": "only these",
  "reachableFrom": [
    "box"
  ]
}
== stderr
== writes

`,
}
