// Code generated by go test -run Golden -update; DO NOT EDIT.

package main

var goldenWant = map[string]string{
	"browser-api-create-all": `== stdout
{
  "created": "every",
  "next": "livellm connect every gives its address and a key or token",
  "type": "controller"
}
== stderr
== writes
POST /v1/workloads/controller {"autodiscover":true,"id":"every"}
`,
	"browser-api-create-named": `== stdout
{
  "created": "scrapers",
  "next": "livellm connect scrapers gives its address and a key or token",
  "type": "controller"
}
== stderr
== writes
POST /v1/workloads/controller {"autodiscover":false,"browsers":["shop","plain"],"id":"scrapers"}
`,
	"browser-api-create-remote": `== stdout
{
  "created": "mix",
  "next": "livellm connect mix gives its address and a key or token",
  "type": "controller"
}
== stderr
== writes
POST /v1/workloads/controller {"autodiscover":false,"browsers":["shop"],"externalBrowsers":[{"id":"office","wsUrl":"wss://o.example"}],"id":"mix"}
`,
	"browser-api-show": `== stdout
{
  "answering": [
    {
      "id": "shop",
      "tabs": 1
    }
  ],
  "browsers": [
    "shop"
  ],
  "drives": "only these",
  "id": "scrapers",
  "ready": true,
  "remoteBrowsers": [],
  "state": "running"
}
== stderr
== writes

`,
	"connect": `== stdout
{
  "cdp": {
    "headers": {
      "Authorization": "Bearer llt_x"
    },
    "url": "wss://shop-cdp.example/devtools/browser/default"
  },
  "engine": "chrome",
  "expiresAt": "2026-10-05T12:00:00Z",
  "how": "connect_over_cdp(cdp.url, headers=cdp.headers)",
  "token": "llt_x",
  "tool": "cdp",
  "type": "browser"
}
== stderr
== writes
POST /v1/workloads/shop/connect {"tool":"cdp"}
`,
	"create-browser": `== stdout
{
  "created": "shop",
  "type": "browser"
}
== stderr
== writes
POST /v1/workloads/browser {"id":"shop"}
`,
	"create-browser-api-file": `== stdout
{
  "created": "scrapers",
  "type": "controller"
}
== stderr
== writes
POST /v1/workloads/controller {"browsers":["shop"],"id":"scrapers"}
`,
	"create-browser-file": `== stdout
{
  "created": "shop",
  "type": "browser"
}
== stderr
== writes
POST /v1/workloads/browser {"id":"shop","languages":["ru-RU","ru"]}
`,
	"create-browser-locale": `== stdout
{
  "created": "shop",
  "type": "browser"
}
== stderr
== writes
POST /v1/workloads/browser {"id":"shop","locale":"ru-RU","timezone":"Europe/Moscow"}
`,
	"ls": `== stdout
{
  "resources": [
    {
      "id": "plain",
      "type": "browser",
      "state": "pending",
      "ready": false,
      "createdBy": "a person"
    },
    {
      "id": "scrapers",
      "type": "controller",
      "state": "running",
      "ready": true,
      "createdBy": "a person"
    },
    {
      "id": "shop",
      "type": "browser",
      "state": "running",
      "ready": true,
      "createdBy": "a person",
      "endpoints": [
        "https://shop-cdp.example"
      ]
    },
    {
      "id": "web",
      "type": "pod",
      "state": "running",
      "ready": true,
      "createdBy": "a person"
    }
  ]
}
== stderr
== writes

`,
	"ls-browser": `== stdout
{
  "resources": [
    {
      "id": "plain",
      "type": "browser",
      "state": "pending",
      "ready": false,
      "createdBy": "a person"
    },
    {
      "id": "shop",
      "type": "browser",
      "state": "running",
      "ready": true,
      "createdBy": "a person",
      "endpoints": [
        "https://shop-cdp.example"
      ]
    }
  ]
}
== stderr
== writes

`,
	"status": `== stdout
{
  "workloads": [
    {
      "endpoints": [
        {
          "url": "https://shop-cdp.example"
        }
      ],
      "id": "shop",
      "phase": "Running",
      "ready": true,
      "type": "browser"
    },
    {
      "id": "plain",
      "phase": "Pending",
      "ready": false,
      "type": "browser"
    },
    {
      "browsers": [
        {
          "id": "shop",
          "tabs": 1
        }
      ],
      "id": "scrapers",
      "phase": "Running",
      "ready": true,
      "type": "controller"
    },
    {
      "id": "web",
      "phase": "Running",
      "ready": true,
      "type": "pod"
    }
  ]
}
== stderr
== writes

`,
	"status-browser": `== stdout
{
  "endpoints": [
    {
      "url": "https://shop-cdp.example"
    }
  ],
  "id": "shop",
  "phase": "Running",
  "ready": true,
  "type": "browser"
}
== stderr
== writes

`,
	"status-browser-api": `== stdout
{
  "browsers": [
    {
      "id": "shop",
      "tabs": 1
    }
  ],
  "id": "scrapers",
  "phase": "Running",
  "ready": true,
  "type": "controller"
}
== stderr
== writes

`,
}
