// Code generated by go test -run GoldenInside -update; DO NOT EDIT.

package main

var goldenInsideWant = map[string]string{
	"api-keys-create-network": `== stdout
{}
== stderr
== writes
POST /v1/keys {"name":"ci","permissions":["network"]}
`,
	"api-keys-set-legacy-names": `== stdout
{}
== stderr
proxies, profiles: no longer a permission; changing a browser's proxies or moving its profile needs none (ask the user first)
== writes
PATCH /v1/keys/k1 {"permissions":["network","proxies","profiles"]}
`,
	"api-keys-set-network": `== stdout
{}
== stderr
== writes
PATCH /v1/keys/k1 {"permissions":["billing","network"]}
`,
	"browser-api-create-reachable-from": `== stdout
{
  "created": "pool2",
  "next": "livellm connect pool2 gives its address and a key or token",
  "type": "controller"
}
== stderr
== writes
POST /v1/workloads/controller {"autodiscover":false,"browsers":["b1"],"id":"pool2","reachableFrom":["edge","box"]}
`,
	"connect-inside": `== stdout
{
  "engine": "postgres",
  "inside": {
    "addresses": [
      {
        "host": "ws-db-rw",
        "port": 5432
      }
    ],
    "alsoFrom": [
      {
        "id": "web",
        "why": "links it"
      }
    ],
    "reachableFrom": []
  },
  "private": {
    "host": "ws-db-rw",
    "port": 5432
  },
  "tool": "api",
  "type": "storage"
}
== stderr
inside the workspace: reachable from nothing else in the workspace; also by web (links it)
== writes
POST /v1/workloads/db/connect {}
`,
	"create-apps-join-no-reachable-from": `== stdout
{
  "created": null
}
== stderr
== writes
POST /v1/workloads {"apps":[{"id":"cron","image":"busybox"}],"join":"web"}
`,
	"create-apps-join-same-reachable-from": `== stdout
{
  "created": null
}
== stderr
== writes
POST /v1/workloads {"apps":[{"id":"cron","image":"busybox","reachableFrom":["edge"]}],"join":"shop"}
`,
	"create-apps-no-reachable-from": `== stdout
{
  "created": null
}
== stderr
== writes
POST /v1/workloads {"apps":[{"id":"front","image":"nginx"}]}
`,
	"create-apps-reachable-from": `== stdout
{
  "created": null
}
== stderr
== writes
POST /v1/workloads {"apps":[{"databases":[{"id":"pg"}],"id":"front","image":"nginx","reachableFrom":["edge"]},{"id":"back","image":"busybox","reachableFrom":["edge"]}],"databases":[{"engine":"postgres","id":"pg"}]}
`,
	"create-browser-reachable-from": `== stdout
{
  "created": "shop",
  "type": "browser"
}
== stderr
== writes
POST /v1/workloads/browser {"id":"shop","reachableFrom":["pool"]}
`,
	"create-file-reachable-from": `== stdout
{
  "created": "api",
  "type": "pod"
}
== stderr
== writes
POST /v1/workloads/pod {"id":"api","image":"nginx","reachableFrom":["*"]}
`,
	"create-file-reachable-from-none": `== stdout
{
  "created": "db2",
  "type": "storage"
}
== stderr
== writes
POST /v1/workloads/storage {"engine":"redis","id":"db2","reachableFrom":[]}
`,
	"reach-set-from": `== stdout
{
  "id": "edge",
  "means": "only these",
  "reachableFrom": [
    "web",
    "box"
  ]
}
== stderr
== writes
PATCH /v1/workloads/edge {"reachableFrom":["web","box"]}
`,
	"reach-set-none": `== stdout
{
  "app": "shop",
  "id": "web",
  "means": "nothing else in the workspace",
  "note": "the whole Composable App shop takes it",
  "reachableFrom": []
}
== stderr
== writes
PATCH /v1/workloads/web {"reachableFrom":[]}
`,
	"reach-set-star": `== stdout
{
  "id": "db",
  "means": "the whole workspace",
  "reachableFrom": [
    "*"
  ]
}
== stderr
== writes
PATCH /v1/workloads/db {"reachableFrom":["*"]}
`,
	"reach-show-absent": `== stdout
{
  "addresses": [
    {
      "host": "ws-cache",
      "port": 6379
    }
  ],
  "alsoFrom": [
    {
      "app": "shop",
      "id": "web",
      "via": "worker",
      "why": "waits for it"
    },
    {
      "app": "shop",
      "id": "worker",
      "why": "waits for it"
    }
  ],
  "change": "livellm reach cache --from a,b | --from \"*\" | --none",
  "id": "cache",
  "means": "the whole workspace",
  "note": "not set yet: reached from the whole workspace, as before",
  "reachableFrom": [
    "*"
  ]
}
== stderr
== writes

`,
	"reach-show-app": `== stdout
{
  "addresses": [
    {
      "host": "ws-web",
      "inStack": "web:8080",
      "name": "http",
      "port": 8080
    },
    {
      "host": "ws-web-raw",
      "inStack": "web:7777",
      "name": "game",
      "port": 7777,
      "protocol": "udp"
    }
  ],
  "alsoFrom": [
    {
      "id": "worker",
      "why": "same app"
    }
  ],
  "app": "shop",
  "change": "livellm reach web --from a,b | --from \"*\" | --none",
  "id": "web",
  "means": "only these",
  "reachableFrom": [
    "edge"
  ]
}
== stderr
== writes

`,
	"reach-show-browser-api": `== stdout
{
  "addresses": [
    {
      "host": "ws-pool",
      "port": 8000
    }
  ],
  "alsoFrom": [],
  "change": "livellm reach pool --from a,b | --from \"*\" | --none",
  "id": "pool",
  "means": "only these",
  "reachableFrom": [
    "edge"
  ]
}
== stderr
== writes

`,
	"reach-show-browser-driven": `== stdout
{
  "addresses": [
    {
      "host": "ws-b1",
      "port": 9222
    },
    {
      "host": "ws-b1",
      "port": 9000
    }
  ],
  "alsoFrom": [
    {
      "id": "pool",
      "through": [
        "edge"
      ],
      "why": "drives it"
    },
    {
      "id": "every",
      "through": [
        "*"
      ],
      "why": "drives it"
    }
  ],
  "change": "livellm reach b1 --from a,b | --from \"*\" | --none",
  "id": "b1",
  "means": "nothing else in the workspace",
  "reachableFrom": []
}
== stderr
== writes

`,
	"reach-show-closed": `== stdout
{
  "alsoFrom": [],
  "change": "livellm reach edge --from a,b | --from \"*\" | --none",
  "id": "edge",
  "means": "nothing else in the workspace",
  "reachableFrom": []
}
== stderr
== writes

`,
	"reach-show-database-linked": `== stdout
{
  "addresses": [
    {
      "host": "ws-db-rw",
      "port": 5432
    }
  ],
  "alsoFrom": [
    {
      "app": "shop",
      "id": "web",
      "why": "links it"
    },
    {
      "app": "shop",
      "id": "worker",
      "via": "web",
      "why": "links it"
    }
  ],
  "change": "livellm reach db --from a,b | --from \"*\" | --none",
  "id": "db",
  "means": "nothing else in the workspace",
  "reachableFrom": []
}
== stderr
== writes

`,
	"reach-show-desktop": `== stdout
{
  "alsoFrom": [],
  "change": "livellm reach desk --from a,b | --from \"*\" | --none",
  "id": "desk",
  "means": "nothing else in the workspace",
  "reachableFrom": []
}
== stderr
== writes

`,
	"reach-show-machine": `== stdout
{
  "addresses": [
    {
      "host": "ws-box",
      "name": "ssh",
      "port": 22
    },
    {
      "host": "ws-box-http",
      "name": "web",
      "port": 8080
    },
    {
      "host": "ws-box",
      "name": "pg",
      "port": 5432
    },
    {
      "host": "ws-box",
      "name": "dns",
      "port": 53,
      "protocol": "udp"
    },
    {
      "host": "ws-box-internal",
      "name": "etcd",
      "port": 2380
    }
  ],
  "alsoFrom": [],
  "change": "livellm reach box --from a,b | --from \"*\" | --none",
  "id": "box",
  "means": "the whole workspace",
  "reachableFrom": [
    "*"
  ]
}
== stderr
== writes

`,
	"reach-show-windows": `== stdout
{
  "addresses": [
    {
      "host": "ws-win",
      "name": "ssh",
      "port": 22
    },
    {
      "host": "ws-win-rdp",
      "name": "rdp",
      "port": 3389
    }
  ],
  "alsoFrom": [],
  "change": "livellm reach win --from a,b | --from \"*\" | --none",
  "id": "win",
  "means": "only these",
  "reachableFrom": [
    "box"
  ]
}
== stderr
== writes

`,
}
